### ISSUE TITLE
Qwen Image Edit 2509 error

### ISSUE THREAD

**Issue by NoMansPC** [Acly/krita-ai-diffusion#2253]
It was working fine before the last update. I don't use it often, but now it gives the following error when it reaches like 20-30% of the progression bar:

Server error: 'list' object has no attribute 'dtype'

Also, I'm not the only one with this error. Someone else in Discussions is having the same error.

**Comment by Acly** [comment]
Nunchaku Qwen nodes are not compatible with the latest ComfyUI, so everyone has this error until they fix it (or go to old Comfy version). Can also use a non-Nunchaku Qwen model.

**Comment by Acly** [comment]
I didn't verify, but supposedly this was fixed in Nunchaku version 1.2.0

Plugin version [v1.46.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.46.0) will install Nunchaku 1.2.0 too.

**Comment by aloisius59** [comment]
I can confirm Qwen is working in 1.46. Too slow for my RTX3070 but works
