### ISSUE TITLE
Lora inside prompt no longer working with 1.16.0

### ISSUE THREAD

**Issue by knapman** [Acly/krita-ai-diffusion#540]
Attempting to use a prompt with a lora ie `<lora:filename:0.8>` results in the message

Error: 'dict' object has no attribute 'name'

Tested a bunch of loras with same result so it doesn't seem to be file specific.

**Comment by Acly** [comment]
Fixed in [v1.16.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.16.1)
